// <auto-generated />
namespace Ternary3.Numbers;

internal readonly struct BytePair(Byte negative, Byte positive)
{
     private readonly UInt16 packed = (UInt16)(((UInt16)negative << 8) | positive);
     public Byte Negative => (Byte)(packed >> 8);
     public Byte Positive => (Byte)packed;
}
