// <auto-generated />
namespace Ternary3;

internal readonly struct UInt16Pair(UInt16 negative, UInt16 positive)
{
     private readonly UInt32 packed = (UInt32)(((UInt32)negative << 16) | positive);
     public UInt16 Negative => (UInt16)(packed >> 16);
     public UInt16 Positive => (UInt16)packed;
}
