// <auto-generated />
namespace Ternary3;

internal readonly struct UInt64Pair(UInt64 negative, UInt64 positive)
{
     private readonly UInt128 packed = (UInt128)(((UInt128)negative << 64) | positive);
     public UInt64 Negative => (UInt64)(packed >> 64);
     public UInt64 Positive => (UInt64)packed;
}
