// <auto-generated />
// ReSharper disable CompareOfFloatsByEqualityOperator
// ReSharper disable IntVariableOverflowInUncheckedContext
// ReSharper disable SuspiciousTypeConversion.Global
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable ConvertIfStatementToSwitchStatement
// ReSharper disable BuiltInTypeReferenceStyle
#nullable enable

namespace Tring.Numbers;

using Operators;
using Operators.Operations;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Numerics;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Represents a 40-trit  signed integer, modeled after the <see cref="Int64"/> type.
/// </summary>
[GeneratedCode("IntT.tt", null)]
public readonly partial struct Int40T : ITernaryInteger<Int40T>
{
    private readonly Int64 value;

    /// <summary>
    ///  Represents the maximum value of a <see cref="Int40T"/>, expressed as a <see cref="Int64"/> This field is constant.
    /// </summary>
    public const Int64 MaxValueConstant = 6078832729528464400;

    /// <summary>
    /// Represents the minimum value of a <see cref="Int40T"/>, expressed as a <see cref="Int64"/> This field is constant.
    /// </summary>
    public const Int64 MinValueConstant = -6078832729528464400;

    /// <summary>
    /// Represents the largest possible value of a <see cref="Int40T"/>. This field is constant.
    /// </summary>
    public static readonly Int40T MaxValue = new(MaxValueConstant);

    /// <summary>
    /// Represents the smallest possible value of a <see cref="Int40T"/>. This field is constant.
    /// </summary>
    public static readonly Int40T MinValue = new(MinValueConstant);

    private Int40T(Int64 value) => this.value = value;
    
     private static Int40T Create(Int32 value) => new(value);
     private static Int40T Create(Int64 value) => new(value.BalancedModulo(MaxValueConstant));
     private static Int40T Create(Int128 value) => new(value.BalancedModulo(MaxValueConstant));

     /// <summary>
/// Defines an implicit conversion of a Int64 to a <see cref="Int40T"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int40T"/> that represents the converted value.</returns>
public static implicit operator Int40T(Int64 value) => Create(value);
     /// <summary>
/// Defines an implicit conversion of a Int40T to a <see cref="Int64"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int64"/> that represents the converted value.</returns>
public static implicit operator Int64(Int40T value) => (Int64)value.value;
     /// <summary>
/// Defines an implicit conversion of a Int32 to a <see cref="Int40T"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int40T"/> that represents the converted value.</returns>
public static implicit operator Int40T(Int32 value) => Create(value);
     /// <summary>
/// Defines an explicit conversion of a Int40T to a <see cref="Int32"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int32"/> that represents the converted value.</returns>
public static explicit operator Int32(Int40T value) => (Int32)value.value;

    /// <summary>
    /// Returns a value indicating whether this instance is equal to a specified object.
    /// </summary>
    /// <param name="obj">An object to compare with this instance.</param>
    /// <returns>
    /// <see langword="true"/> if <paramref name="obj"/> is an instance of <see cref="Int40T"/> or a compatible numeric type
    /// and equals the value of this instance; otherwise, <see langword="false"/>.
    /// </returns>
    public override bool Equals(object? obj)
    {
        switch (obj)
        {
            case null: return false;
            case Int40T other: return value == other.value;
            case int typed: return value == typed;
            case long int64: return value == int64;
            case short int16: return value == int16;
            case byte byteVal: return value == byteVal;
            case sbyte sbyteVal: return value == sbyteVal;
            case uint uint32: return value == uint32;
            case ulong uint64: return value == (Int64)uint64;
            case ushort uint16: return value == uint16;
            case float singleValue: return singleValue.Equals(value);
            case double doubleValue: return doubleValue.Equals(value);
            case decimal decimalValue: return decimalValue.Equals(value);
            case char charVal: return value == charVal;
            case IConvertible conv:
                try
                {
                    // ReSharper disable once SwitchStatementHandlesSomeKnownEnumValuesWithDefault
                    switch (conv.GetTypeCode())
                    {
                        case TypeCode.Int16: return value == conv.ToInt16(null);
                        case TypeCode.UInt16: return value == conv.ToUInt16(null);
                        case TypeCode.Int32: return value == conv.ToInt32(null);
                        case TypeCode.UInt32: return value == conv.ToUInt32(null);
                        case TypeCode.Int64: return value == conv.ToInt64(null);
                        case TypeCode.UInt64: return value == (Int64)conv.ToUInt64(null);
                        case TypeCode.Byte: return value == conv.ToByte(null);
                        case TypeCode.SByte: return value == conv.ToSByte(null);
                        case TypeCode.Single: return conv.ToSingle(null).Equals(value);
                        case TypeCode.Double: return conv.ToDouble(null).Equals(value);
                        case TypeCode.Decimal: return conv.ToDecimal(null).Equals(value);
                    }
                }
                catch
                {
                    return false;
                }

                break;
        }

        return obj.Equals(value);
    }

    /// <summary>
    /// Returns a value indicating whether this instance is equal to a specified <see cref="Int40T"/> value.
    /// </summary>
    /// <param name="other">A <see cref="Int40T"/> value to compare to this instance.</param>
    /// <returns><see langword="true"/> if <paramref name="other"/> has the same value as this instance; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Int40T other) => value == other.value;

    /// <summary>
    /// Returns a value indicating whether this instance is equal to a specified <see cref="Int64"/> value.
    /// </summary>
    /// <param name="other">A <see cref="Int64"/> value to compare to this instance.</param>
    /// <returns><see langword="true"/> if <paramref name="other"/> has the same value as this instance; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Int64 other) => value == other;

    /// <summary>
    /// Returns the hash code for this instance.
    /// </summary>
    /// <returns>A 32-bit signed integer hash code.</returns>
    public override int GetHashCode() => value.GetHashCode();

    #region Equality Operators

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int40T"/> instances are equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator ==(IConvertible left, Int40T right) => right.Equals(left);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int40T"/> instances are not equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator !=(IConvertible left, Int40T right) => !right.Equals(left);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int40T"/> instances are equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator ==(Int40T left, IConvertible right) => left.Equals(right);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int40T"/> instances are not equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator !=(Int40T left, IConvertible right) => !left.Equals(right);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int40T"/> instances are equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator ==(Int40T left, Int40T right) => left.value == right.value;

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int40T"/> instances are not equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator !=(Int40T left, Int40T right) => left.value != right.value;

    #endregion

    #region Arithmetic Operators
    
    public static Int40T operator +(Int40T left, Int40T right) => Create((Int128)left.value + right.value);
    public static Int40T operator -(Int40T left, Int40T right) => Create((Int128)left.value - right.value);
    public static Int40T operator *(Int40T left, Int40T right) => Create((Int128)left.value * right.value);
    public static Int40T operator /(Int40T left, Int40T right) => Create(left.value / right.value);
    public static Int40T operator %(Int40T left, Int40T right) => Create(left.value % right.value);
    public static Int40T operator -(Int40T value) => Create(-value.value);
    public static Int40T operator +(Int40T value) => value;
    public static Int40T operator +(Int40T left, Int64 right) => Create((Int128)left.value + right);
    public static Int40T operator +(Int64 left, Int40T right) => Create((Int128)left + right.value);
    public static Int40T operator -(Int40T left, Int64 right) => Create((Int128)left.value - right);
    public static Int40T operator -(Int64 left, Int40T right) => Create((Int128)left - right.value);
    public static Int40T operator *(Int40T left, Int64 right) => Create((Int128)left.value * right);
    public static Int40T operator *(Int64 left, Int40T right) => Create((Int128)left * right.value);
    public static Int40T operator /(Int40T left, Int64 right) => Create(left.value / right);
    public static Int40T operator /(Int64 left, Int40T right) => Create(left / right.value);
    public static Int40T operator %(Int40T left, Int64 right) => Create(left.value % right);
    public static Int40T operator %(Int64 left, Int40T right) => Create(left % right.value);
    #endregion
    
    #region Comparison Operators

    // Comparison operators with Int40T
    public static bool operator >(Int40T left, Int40T right) => left.value > right.value;
    public static bool operator <(Int40T left, Int40T right) => left.value < right.value;
    public static bool operator >=(Int40T left, Int40T right) => left.value >= right.value;
    public static bool operator <=(Int40T left, Int40T right) => left.value <= right.value;
    
    // Comparison operators with sbyte
    public static bool operator >(Int40T left, sbyte right) => left.value > right;
    public static bool operator <(Int40T left, sbyte right) => left.value < right;
    public static bool operator >=(Int40T left, sbyte right) => left.value >= right;
    public static bool operator <=(Int40T left, sbyte right) => left.value <= right;

    public static bool operator >(sbyte left, Int40T right) => left > right.value;
    public static bool operator <(sbyte left, Int40T right) => left < right.value;
    public static bool operator >=(sbyte left, Int40T right) => left >= right.value;
    public static bool operator <=(sbyte left, Int40T right) => left <= right.value;
    
    // Comparison operators with byte
    public static bool operator >(Int40T left, byte right) => left.value > right;
    public static bool operator <(Int40T left, byte right) => left.value < right;
    public static bool operator >=(Int40T left, byte right) => left.value >= right;
    public static bool operator <=(Int40T left, byte right) => left.value <= right;

    public static bool operator >(byte left, Int40T right) => left > right.value;
    public static bool operator <(byte left, Int40T right) => left < right.value;
    public static bool operator >=(byte left, Int40T right) => left >= right.value;
    public static bool operator <=(byte left, Int40T right) => left <= right.value;
    
    // Comparison operators with int
    public static bool operator >(Int40T left, int right) => left.value > right;
    public static bool operator <(Int40T left, int right) => left.value < right;
    public static bool operator >=(Int40T left, int right) => left.value >= right;
    public static bool operator <=(Int40T left, int right) => left.value <= right;

    public static bool operator >(int left, Int40T right) => left > right.value;
    public static bool operator <(int left, Int40T right) => left < right.value;
    public static bool operator >=(int left, Int40T right) => left >= right.value;
    public static bool operator <=(int left, Int40T right) => left <= right.value;
    
    // Comparison operators with uint
    public static bool operator >(Int40T left, uint right) => left.value > right;
    public static bool operator <(Int40T left, uint right) => left.value < right;
    public static bool operator >=(Int40T left, uint right) => left.value >= right;
    public static bool operator <=(Int40T left, uint right) => left.value <= right;

    public static bool operator >(uint left, Int40T right) => left > right.value;
    public static bool operator <(uint left, Int40T right) => left < right.value;
    public static bool operator >=(uint left, Int40T right) => left >= right.value;
    public static bool operator <=(uint left, Int40T right) => left <= right.value;
    
    // Comparison operators with short
    public static bool operator >(Int40T left, short right) => left.value > right;
    public static bool operator <(Int40T left, short right) => left.value < right;
    public static bool operator >=(Int40T left, short right) => left.value >= right;
    public static bool operator <=(Int40T left, short right) => left.value <= right;

    public static bool operator >(short left, Int40T right) => left > right.value;
    public static bool operator <(short left, Int40T right) => left < right.value;
    public static bool operator >=(short left, Int40T right) => left >= right.value;
    public static bool operator <=(short left, Int40T right) => left <= right.value;
    
    // Comparison operators with ushort
    public static bool operator >(Int40T left, ushort right) => left.value > right;
    public static bool operator <(Int40T left, ushort right) => left.value < right;
    public static bool operator >=(Int40T left, ushort right) => left.value >= right;
    public static bool operator <=(Int40T left, ushort right) => left.value <= right;

    public static bool operator >(ushort left, Int40T right) => left > right.value;
    public static bool operator <(ushort left, Int40T right) => left < right.value;
    public static bool operator >=(ushort left, Int40T right) => left >= right.value;
    public static bool operator <=(ushort left, Int40T right) => left <= right.value;
    
    // Comparison operators with long
    public static bool operator >(Int40T left, long right) => left.value > right;
    public static bool operator <(Int40T left, long right) => left.value < right;
    public static bool operator >=(Int40T left, long right) => left.value >= right;
    public static bool operator <=(Int40T left, long right) => left.value <= right;

    public static bool operator >(long left, Int40T right) => left > right.value;
    public static bool operator <(long left, Int40T right) => left < right.value;
    public static bool operator >=(long left, Int40T right) => left >= right.value;
    public static bool operator <=(long left, Int40T right) => left <= right.value;
    
    // Comparison operators with ulong
    public static bool operator >(Int40T left, ulong right) => left.CompareTo(right) > 0;
    public static bool operator <(Int40T left, ulong right) => left.CompareTo(right) < 0;
    public static bool operator >=(Int40T left, ulong right) => left.CompareTo(right) >= 0;
    public static bool operator <=(Int40T left, ulong right) => left.CompareTo(right) <= 0;

    public static bool operator >(ulong left, Int40T right) => right.CompareTo(left) < 0;
    public static bool operator <(ulong left, Int40T right) => right.CompareTo(left) > 0;
    public static bool operator >=(ulong left, Int40T right) => right.CompareTo(left) <= 0;
    public static bool operator <=(ulong left, Int40T right) => right.CompareTo(left) >= 0;
     
    // Comparison operators with float
    public static bool operator >(Int40T left, float right) => left.value > right;
    public static bool operator <(Int40T left, float right) => left.value < right;
    public static bool operator >=(Int40T left, float right) => left.value >= right;
    public static bool operator <=(Int40T left, float right) => left.value <= right;

    public static bool operator >(float left, Int40T right) => left > right.value;
    public static bool operator <(float left, Int40T right) => left < right.value;
    public static bool operator >=(float left, Int40T right) => left >= right.value;
    public static bool operator <=(float left, Int40T right) => left <= right.value;
     
    // Comparison operators with double
    public static bool operator >(Int40T left, double right) => left.value > right;
    public static bool operator <(Int40T left, double right) => left.value < right;
    public static bool operator >=(Int40T left, double right) => left.value >= right;
    public static bool operator <=(Int40T left, double right) => left.value <= right;

    public static bool operator >(double left, Int40T right) => left > right.value;
    public static bool operator <(double left, Int40T right) => left < right.value;
    public static bool operator >=(double left, Int40T right) => left >= right.value;
    public static bool operator <=(double left, Int40T right) => left <= right.value;
     
    // Comparison operators with decimal
    public static bool operator >(Int40T left, decimal right) => left.value > right;
    public static bool operator <(Int40T left, decimal right) => left.value < right;
    public static bool operator >=(Int40T left, decimal right) => left.value >= right;
    public static bool operator <=(Int40T left, decimal right) => left.value <= right;

    public static bool operator >(decimal left, Int40T right) => left > right.value;
    public static bool operator <(decimal left, Int40T right) => left < right.value;
    public static bool operator >=(decimal left, Int40T right) => left >= right.value;
    public static bool operator <=(decimal left, Int40T right) => left <= right.value;
     
    // Comparison operators with IComparable
    public static bool operator >(Int40T left, IComparable right) => left.CompareTo(right) > 0;
    public static bool operator <(Int40T left, IComparable right) => left.CompareTo(right) < 0;
    public static bool operator >=(Int40T left, IComparable right) => left.CompareTo(right) >= 0;
    public static bool operator <=(Int40T left, IComparable right) => left.CompareTo(right) <= 0;

    public static bool operator >(IComparable left, Int40T right) => right.CompareTo(left) < 0;
    public static bool operator <(IComparable left, Int40T right) => right.CompareTo(left) > 0;
    public static bool operator >=(IComparable left, Int40T right) => right.CompareTo(left) <= 0;
    public static bool operator <=(IComparable left, Int40T right) => right.CompareTo(left) >= 0;

    #endregion

    // ToString implementation
    public override string ToString() => value.ToString();
    public string ToString(string? format) => value.ToString(format);
    public string ToString(IFormatProvider? provider) => value.ToString(provider);
    public string ToString(string? format, IFormatProvider? provider) => value.ToString(format, provider);

    // Parsing methods

    /// <summary>
    /// Converts the string representation of a number to its <see cref="Int40T"/> equivalent.
    /// </summary>
    /// <param name="s">A string containing a number to convert.</param>
    /// <returns>A <see cref="Int40T"/> equivalent to the number contained in <paramref name="s"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="s"/> is <see langword="null"/>.</exception>
    /// <exception cref="FormatException"><paramref name="s"/> is not in the correct format.</exception>
    /// <exception cref="OverflowException"><paramref name="s"/> represents a number less than <see cref="Int40T.MinValue"/> or greater than <see cref="Int40T.MaxValue"/>.</exception>
    public static Int40T Parse(string s) => Create(Int64.Parse(s));

    /// <summary>
    /// Converts the string representation of a number in a specified style to its <see cref="Int40T"/> equivalent.
    /// </summary>
    /// <param name="s">A string containing a number to convert.</param>
    /// <param name="style">A bitwise combination of enumeration values that indicate the style elements that can be present in <paramref name="s"/>.</param>
    /// <returns>A <see cref="Int40T"/> equivalent to the number contained in <paramref name="s"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="s"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException"><paramref name="style"/> is not a <see cref="NumberStyles"/> value or <paramref name="style"/> includes the <see cref="NumberStyles.AllowHexSpecifier"/> value.</exception>
    /// <exception cref="FormatException"><paramref name="s"/> is not in a format compliant with <paramref name="style"/>.</exception>
    /// <exception cref="OverflowException"><paramref name="s"/> represents a number less than <see cref="Int40T.MinValue"/> or greater than <see cref="Int40T.MaxValue"/>.</exception>
    public static Int40T Parse(string s, NumberStyles style) => Create(Int64.Parse(s, style));

    /// <summary>
    /// Tries to convert the string representation of a number to its <see cref="Int40T"/> equivalent, and returns a value that indicates whether the conversion succeeded.
    /// </summary>
    /// <param name="s">A string containing a number to convert.</param>
    /// <param name="result">When this method returns, contains the <see cref="Int40T"/> value equivalent to the number contained in <paramref name="s"/> if the conversion succeeded, or zero if the conversion failed. This parameter is passed uninitialized.</param>
    /// <returns><see langword="true"/> if <paramref name="s"/> was converted successfully; otherwise, <see langword="false"/>.</returns>
    public static bool TryParse(string? s, out Int40T result)
    {
        bool success = Int64.TryParse(s, out Int64 value);
        result = new Int40T(value);
        return success;
    }

    /// <summary>
    /// Compares this instance to a specified object and returns an indication of their relative values.
    /// </summary>
    /// <param name="obj">An object to compare, or <see langword="null"/>.</param>
    /// <returns>
    /// A signed number indicating the relative values of this instance and <paramref name="obj"/>.
    /// Return Value Description:
    /// Less than zero: This instance is less than <paramref name="obj"/>.
    /// Zero: This instance is equal to <paramref name="obj"/>.
    /// Greater than zero: This instance is greater than <paramref name="obj"/> or <paramref name="obj"/> is <see langword="null"/>.
    /// </returns>
    /// <exception cref="ArgumentException"><paramref name="obj"/> is not a <see cref="Int40T"/> or a type that can be converted to an integer.</exception>
    public int CompareTo(object? obj)
    {
        if (obj == null) return 1;
        if (obj is Int40T other) return CompareTo(other);

        // For large numeric types that exceed Int40T's range, return -1 if greater than MaxValue, 1 if less than MinValue
        try
        {
            if (obj is Int64 typed) return value.CompareTo(typed);
            if (obj is long int64)
            {
                return int64 switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int64)int64)
                };
            }

            if (obj is uint uint32)
            {
                return value.CompareTo((Int64)uint32);
            }

            if (obj is ulong uint64)
            {
                return uint64 > (long)MaxValueConstant ? -1 : value.CompareTo((Int64)uint64);
            }

            if (obj is short int16) return value.CompareTo(int16);
            if (obj is ushort uint16) return value.CompareTo(uint16);
            if (obj is byte byteVal) return value.CompareTo(byteVal);
            if (obj is sbyte sbyteVal) return value.CompareTo(sbyteVal);
            if (obj is float singleValue)
            {
                return singleValue switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int64)singleValue)
                };
            }

            if (obj is double doubleValue)
            {
                return doubleValue switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int64)doubleValue)
                };
            }

            if (obj is decimal decimalValue)
            {
                return decimalValue switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int64)decimalValue)
                };
            }

            if (obj is IConvertible convertible)
            {
                switch (convertible.GetTypeCode())
                {
                    case TypeCode.Int16:
                    case TypeCode.UInt16:
                    case TypeCode.Byte:
                    case TypeCode.SByte:
                        return value.CompareTo(convertible.ToInt32(null));
                    case TypeCode.Int32:
                        return value.CompareTo(convertible.ToInt32(null));
                    case TypeCode.UInt32:
                        var uint32Value = convertible.ToUInt32(null);
                        
                        return value.CompareTo((Int64)uint32Value);
                    case TypeCode.Int64:
                        var int64Value = convertible.ToInt64(null);
                        if (int64Value > MaxValueConstant) return -1;
                        if (int64Value < MinValueConstant) return 1;
                        return value.CompareTo((Int64)(int64Value));
                    case TypeCode.UInt64:
                        var uint64Value = convertible.ToUInt64(null);
                        if (uint64Value > (long)MaxValueConstant) return -1;
                        return value.CompareTo((Int64)uint64Value);
                    case TypeCode.Single:
                        var singleVal = convertible.ToSingle(null);
                        if (singleVal > MaxValueConstant) return -1;
                        if (singleVal < MinValueConstant) return 1;
                        return value.CompareTo((Int64)singleVal);
                    case TypeCode.Double:
                        var doubleVal = convertible.ToDouble(null);
                        if (doubleVal > MaxValueConstant) return -1;
                        if (doubleVal < MinValueConstant) return 1;
                        return value.CompareTo((Int64)doubleVal);
                    case TypeCode.Decimal:
                        var decimalVal = convertible.ToDecimal(null);
                        if (decimalVal > MaxValueConstant) return -1;
                        if (decimalVal < MinValueConstant) return 1;
                        return value.CompareTo((Int64)decimalVal);
                }
            }
        }
        catch (OverflowException)
        {
            // If conversion fails due to overflow, we can assume the value is outside our range
            return -1;
        }

        throw new ArgumentException("Object is not a valid type for comparison", nameof(obj));
    }

    /// <summary>
    /// Compares this instance to a specified <see cref="Int40T"/> object and returns an indication of their relative values.
    /// </summary>
    /// <param name="other">An <see cref="Int40T"/> object to compare.</param>
    /// <returns>
    /// A signed number indicating the relative values of this instance and <paramref name="other"/>.
    /// Return Value Description:
    /// Less than zero: This instance is less than <paramref name="other"/>.
    /// Zero: This instance is equal to <paramref name="other"/>.
    /// Greater than zero: This instance is greater than <paramref name="other"/>.
    /// </returns>
    public int CompareTo(Int40T other) => value.CompareTo(other.value);

    #region IConvertible Implementation

    public TypeCode GetTypeCode() => TypeCode.Int32;

    bool IConvertible.ToBoolean(IFormatProvider? provider) => value != 0;
    char IConvertible.ToChar(IFormatProvider? provider) => Convert.ToChar(value);
    sbyte IConvertible.ToSByte(IFormatProvider? provider) => Convert.ToSByte(value);
    byte IConvertible.ToByte(IFormatProvider? provider) => Convert.ToByte(value);
    short IConvertible.ToInt16(IFormatProvider? provider) => Convert.ToInt16(value);
    ushort IConvertible.ToUInt16(IFormatProvider? provider) => Convert.ToUInt16(value);
    int IConvertible.ToInt32(IFormatProvider? provider) => Convert.ToInt32(value);
    uint IConvertible.ToUInt32(IFormatProvider? provider) => Convert.ToUInt32(value);
    long IConvertible.ToInt64(IFormatProvider? provider) => Convert.ToInt64(value);
    ulong IConvertible.ToUInt64(IFormatProvider? provider) => Convert.ToUInt64(value);
    float IConvertible.ToSingle(IFormatProvider? provider) => Convert.ToSingle(value);
    double IConvertible.ToDouble(IFormatProvider? provider) => Convert.ToDouble(value);
    decimal IConvertible.ToDecimal(IFormatProvider? provider) => Convert.ToDecimal(value);
    DateTime IConvertible.ToDateTime(IFormatProvider? provider) => throw new InvalidCastException();
    string IConvertible.ToString(IFormatProvider? provider) => value.ToString(provider);

    object IConvertible.ToType(Type conversionType, IFormatProvider? provider) =>
        Convert.ChangeType(value, conversionType, provider);

    #endregion

    #region IUtf8SpanFormattable Implementation

    bool IUtf8SpanFormattable.TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        if (!value.TryFormat(stackalloc char[32], out int charsWritten, format, provider))
        {
            bytesWritten = 0;
            return false;
        }

        // Get UTF8 byte count for the character length
        var byteCount = System.Text.Encoding.UTF8.GetMaxByteCount(charsWritten);

        if (utf8Destination.Length < byteCount)
        {
            bytesWritten = 0;
            return false;
        }

        // Convert to string since we can't go directly from ReadOnlySpan<char> to UTF8
        var str = value.ToString(format.ToString(), provider);
        bytesWritten = System.Text.Encoding.UTF8.GetBytes(str, utf8Destination);
        return true;
    }

    #endregion

    #region IIncrementOperators/IDecrementOperators Implementation

    public static Int40T operator ++(Int40T value) => Create(value.value + 1);
    public static Int40T operator --(Int40T value) => Create(value.value - 1);

    #endregion

    static bool IEqualityOperators<Int40T, Int40T, bool>.operator ==(Int40T left, Int40T right) => left.value == right.value;
    static bool IEqualityOperators<Int40T, Int40T, bool>.operator !=(Int40T left, Int40T right) => left.value != right.value;

    #region Binary Operations

    
static Int40T ITritwiseOperators<Int40T, Int40T, Int40T>.operator &(Int40T left, Int40T right) => Create(Operation.And(left.value, right.value));
static Int40T ITritwiseOperators<Int40T, Int40T, Int40T>.operator |(Int40T left, Int40T right) => Create(Operation.Or(left.value, right.value));
static Int40T ITritwiseOperators<Int40T, Int40T, Int40T>.operator ^(Int40T left, Int40T right) => Create(Operation.Xor(left.value, right.value));
static Int40T IShiftOperators<Int40T, int, Int40T>.operator <<(Int40T value, int shiftAmount) => Create(value.value.Shift(-shiftAmount));
static Int40T IShiftOperators<Int40T, int, Int40T>.operator >> (Int40T value, int shiftAmount) => Create(value.value.Shift(shiftAmount));
static Int40T IShiftOperators<Int40T, int, Int40T>.operator >>> (Int40T value, int shiftAmount) => Create(value.value.Shift(shiftAmount));

    #endregion

    #region Interface Static Members

    static Int40T ISignedNumber<Int40T>.NegativeOne => new(-1);
    static Int40T INumberBase<Int40T>.One => new(1);
    static Int40T INumberBase<Int40T>.Zero => new(0);
    static Int40T IAdditiveIdentity<Int40T, Int40T>.AdditiveIdentity => new(0);
    static Int40T IMultiplicativeIdentity<Int40T, Int40T>.MultiplicativeIdentity => new(1);

    static bool INumberBase<Int40T>.IsCanonical(Int40T value) => true;
    static bool INumberBase<Int40T>.IsComplexNumber(Int40T value) => false;
    static bool INumberBase<Int40T>.IsEvenInteger(Int40T value) => value.value % 2 == 0;
    static bool INumberBase<Int40T>.IsFinite(Int40T value) => true;
    static bool INumberBase<Int40T>.IsImaginaryNumber(Int40T value) => false;
    static bool INumberBase<Int40T>.IsInfinity(Int40T value) => false;
    static bool INumberBase<Int40T>.IsInteger(Int40T value) => true;
    static bool INumberBase<Int40T>.IsNaN(Int40T value) => false;
    static bool INumberBase<Int40T>.IsNegative(Int40T value) => value.value < 0;
    static bool INumberBase<Int40T>.IsNegativeInfinity(Int40T value) => false;
    static bool INumberBase<Int40T>.IsNormal(Int40T value) => value.value != 0;
    static bool INumberBase<Int40T>.IsOddInteger(Int40T value) => value.value % 2 != 0;
    static bool INumberBase<Int40T>.IsPositive(Int40T value) => value.value > 0;
    static bool INumberBase<Int40T>.IsPositiveInfinity(Int40T value) => false;
    static bool INumberBase<Int40T>.IsRealNumber(Int40T value) => true;
    static bool INumberBase<Int40T>.IsSubnormal(Int40T value) => false;
    static bool INumberBase<Int40T>.IsZero(Int40T value) => value.value == 0;

    static Int40T INumberBase<Int40T>.MaxMagnitude(Int40T x, Int40T y) =>
        Math.Abs(x.value) > Math.Abs(y.value) ? x : y;

    static Int40T INumberBase<Int40T>.MaxMagnitudeNumber(Int40T x, Int40T y) =>
        Math.Abs(x.value) > Math.Abs(y.value) ? x : y;

    static Int40T INumberBase<Int40T>.MinMagnitude(Int40T x, Int40T y) =>
        Math.Abs(x.value) < Math.Abs(y.value) ? x : y;

    static Int40T INumberBase<Int40T>.MinMagnitudeNumber(Int40T x, Int40T y) =>
        Math.Abs(x.value) < Math.Abs(y.value) ? x : y;

    static int INumberBase<Int40T>.Radix => 2;

    static Int40T INumberBase<Int40T>.Abs(Int40T value) =>
        value.value < 0 ? new((Int64)(-value.value)) : value;

    static Int40T INumberBase<Int40T>.Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) =>
        Create(Int64.Parse(s, style, provider));

    static Int40T INumberBase<Int40T>.Parse(string s, NumberStyles style, IFormatProvider? provider) =>
        Create(Int64.Parse(s, style, provider));

    static bool INumberBase<Int40T>.TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out Int40T result)
    {
        if (Int64.TryParse(s, style, provider, out var parsed))
        {
            result = Create(parsed);
            return true;
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int40T>.TryParse([NotNullWhen(true)] string? s, NumberStyles style, IFormatProvider? provider, out Int40T result)
    {
        if (Int64.TryParse(s, style, provider, out var parsed))
        {
            result = Create(parsed);
            return true;
        }

        result = default;
        return false;
    }

    #endregion

    #region ISpanFormattable/ISpanParsable Implementation

    static Int40T ISpanParsable<Int40T>.Parse(ReadOnlySpan<char> s, IFormatProvider? provider) =>
        new(Int64.Parse(s, NumberStyles.Integer, provider));

    static bool ISpanParsable<Int40T>.TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Int40T result)
    {
        if (Int64.TryParse(s, NumberStyles.Integer, provider, out var value))
        {
            result = new(value);
            return true;
        }

        result = default;
        return false;
    }

    bool ISpanFormattable.TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) =>
        value.TryFormat(destination, out charsWritten, format.ToString(), provider);

    static Int40T IParsable<Int40T>.Parse(string s, IFormatProvider? provider) =>
        new(Int64.Parse(s, NumberStyles.Integer, provider));

    static bool IParsable<Int40T>.TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out Int40T result)
    {
        if (Int64.TryParse(s, NumberStyles.Integer, provider, out var value))
        {
            result = new(value);
            return true;
        }

        result = default;
        return false;
    }

    #endregion

    #region Generic Conversions

    static bool INumberBase<Int40T>.TryConvertFromChecked<TOther>(TOther value, out Int40T result)
    {
        if (value is IConvertible conv)
        {
            try
            {
                var intValue = conv.ToInt64(null);
                if (intValue >= MinValueConstant && intValue <= MaxValueConstant)
                {
                    result = Create(intValue);
                    return true;
                }
            }
            catch
            {
                // Fall through to default
            }
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int40T>.TryConvertFromSaturating<TOther>(TOther value, out Int40T result)
    {
        if (value is IConvertible conv)
        {
            try
            {
                var intValue = conv.ToInt64(null);
                result = Create(intValue);
                return true;
            }
            catch
            {
                // Fall through to default
            }
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int40T>.TryConvertFromTruncating<TOther>(TOther value, out Int40T result)
    {
        if (value is IConvertible conv)
        {
            try
            {
                var intValue = conv.ToInt64(null);
                result = Create(intValue);
                return true;
            }
            catch
            {
                // Fall through to default
            }
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int40T>.TryConvertToChecked<TOther>(Int40T value, [MaybeNullWhen(false)] out TOther result)
        where TOther : default
    {
        if (typeof(TOther) == typeof(Int64))
        {
            result = (TOther)(object)value.value;
            return true;
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int40T>.TryConvertToSaturating<TOther>(Int40T value, [MaybeNullWhen(false)] out TOther result)
        where TOther : default
    {
        if (typeof(TOther) == typeof(Int64))
        {
            result = (TOther)(object)value.value;
            return true;
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int40T>.TryConvertToTruncating<TOther>(Int40T value, [MaybeNullWhen(false)] out TOther result)
        where TOther : default
    {
        if (typeof(TOther) == typeof(Int64))
        {
            result = (TOther)(object)value.value;
            return true;
        }

        result = default;
        return false;
    }

    #endregion
}