// This file is auto-generated by TernaryNumbers.tt
// Do not modify this file directly as changes will be overwritten
namespace Tring.Numbers;

/// <summary>
/// This file serves as a marker to indicate the T4 template has run successfully.
/// Look for individual generated files for each ternary number type.
/// </summary>
internal static class TernaryNumberGenerator
{
    public static readonly string LastGenerated = "2025-06-05 13:44:37";
}

