// <auto-generated />
namespace Tring.Numbers;

using Operators.Operations;

public readonly struct LookupTritArray9Operator
{
    private readonly TritArray9 trits;
    private readonly BinaryOperationBuilder<UInt16> builder;

    internal LookupTritArray9Operator(TritArray9 trits, TritLookupTable table)
    {
        this.trits = trits;
        this.builder = new(table);
    }

    internal LookupTritArray9Operator(TritArray9 trits, Trit[,] table)
        : this(trits, new TritLookupTable(table))
    {
    }

    internal LookupTritArray9Operator(TritArray9 trits, ReadOnlySpan<Trit> table)
        : this(trits, new TritLookupTable(table))
    {
    }

    internal LookupTritArray9Operator(TritArray9 trits, Func<Trit, Trit, Trit> operation)
        : this(trits, new TritLookupTable(operation))
    {
    }

    public static TritArray9 operator |(LookupTritArray9Operator left, TritArray9 right)
    {
        left.builder.Build()(left.trits.Negative, left.trits.Positive, right.Negative, right.Positive, out var negative, out var positive);
        return new() { Negative = negative, Positive = positive };
    }
}