// <auto-generated />
#nullable enable
namespace Ternary3;

using Integers;
using Formatting;
using Operators;
using Operators.Operations;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Numerics;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Represents a 9-trit  signed integer, modeled after the <see cref="Int16"/> type.
/// </summary>
[GeneratedCode("IntT.tt", null)]
public readonly partial struct Int9T : ITernaryInteger<Int9T>
{
    private readonly Int16 value;

    /// <summary>
    ///  Represents the maximum value of a <see cref="Int9T"/>, expressed as a <see cref="Int16"/> This field is constant.
    /// </summary>
    public const Int16 MaxValueConstant = 9841;

    /// <summary>
    /// Represents the minimum value of a <see cref="Int9T"/>, expressed as a <see cref="Int16"/> This field is constant.
    /// </summary>
    public const Int16 MinValueConstant = -9841;

    /// <summary>
    /// Represents the largest possible value of a <see cref="Int9T"/>. This field is constant.
    /// </summary>
    public static readonly Int9T MaxValue = new(MaxValueConstant);

    /// <summary>
    /// Represents the smallest possible value of a <see cref="Int9T"/>. This field is constant.
    /// </summary>
    public static readonly Int9T MinValue = new(MinValueConstant);

    private Int9T(Int16 value) => this.value = value;
    
     private static Int9T Create(Int16 value) => new((Int16)((Int32)value).BalancedModulo((Int32)MaxValueConstant));
     private static Int9T Create(Int32 value) => new((Int16)(value.BalancedModulo((Int32)MaxValueConstant)));
     private static Int9T Create(Int64 value) => new((Int16)(value.BalancedModulo((Int64)MaxValueConstant)));
     private static Int9T Create(Int128 value) => new((Int16)value.BalancedModulo((Int64)MaxValueConstant));

     /// <summary>
/// Defines an implicit conversion of a Int16 to a <see cref="Int9T"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int9T"/> that represents the converted value.</returns>
public static implicit operator Int9T(Int16 value) => Create(value);
     /// <summary>
/// Defines an implicit conversion of a Int9T to a <see cref="Int16"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int16"/> that represents the converted value.</returns>
public static implicit operator Int16(Int9T value) => (Int16)value.value;
     /// <summary>
/// Defines an explicit conversion of a Int32 to a <see cref="Int9T"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int9T"/> that represents the converted value.</returns>
public static explicit operator Int9T(Int32 value) => Create(value);
     /// <summary>
/// Defines an implicit conversion of a Int9T to a <see cref="Int32"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int32"/> that represents the converted value.</returns>
public static implicit operator Int32(Int9T value) => (Int32)value.value;
     /// <summary>
/// Defines an explicit conversion of a Int64 to a <see cref="Int9T"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int9T"/> that represents the converted value.</returns>
public static explicit operator Int9T(Int64 value) => Create(value);
     /// <summary>
/// Defines an implicit conversion of a Int9T to a <see cref="Int64"/>.
/// </summary>
/// <param name="value">The value to convert.</param>
/// <returns>A <see cref="Int64"/> that represents the converted value.</returns>
public static implicit operator Int64(Int9T value) => (Int64)value.value;

    /// <summary>
    /// Returns a value indicating whether this instance is equal to a specified object.
    /// </summary>
    /// <param name="obj">An object to compare with this instance.</param>
    /// <returns>
    /// <see langword="true"/> if <paramref name="obj"/> is an instance of <see cref="Int9T"/> or a compatible numeric type
    /// and equals the value of this instance; otherwise, <see langword="false"/>.
    /// </returns>
    public override bool Equals(object? obj)
    {
        switch (obj)
        {
            case null: return false;
            case Int9T other: return value == other.value;
            case int typed: return value == typed;
            case long int64: return value == int64;
            case short int16: return value == int16;
            case byte byteVal: return value == byteVal;
            case sbyte sbyteVal: return value == sbyteVal;
            case uint uint32: return value == uint32;
            case ulong uint64: return value == (Int16)uint64;
            case ushort uint16: return value == uint16;
            case float singleValue: return singleValue.Equals(value);
            case double doubleValue: return doubleValue.Equals(value);
            case decimal decimalValue: return decimalValue.Equals(value);
            case char charVal: return value == charVal;
            case IConvertible conv:
                try
                {
                    // ReSharper disable once SwitchStatementHandlesSomeKnownEnumValuesWithDefault
                    switch (conv.GetTypeCode())
                    {
                        case TypeCode.Int16: return value == conv.ToInt16(null);
                        case TypeCode.UInt16: return value == conv.ToUInt16(null);
                        case TypeCode.Int32: return value == conv.ToInt32(null);
                        case TypeCode.UInt32: return value == conv.ToUInt32(null);
                        case TypeCode.Int64: return value == conv.ToInt64(null);
                        case TypeCode.UInt64: return value == (Int16)conv.ToUInt64(null);
                        case TypeCode.Byte: return value == conv.ToByte(null);
                        case TypeCode.SByte: return value == conv.ToSByte(null);
                        case TypeCode.Single: return conv.ToSingle(null).Equals(value);
                        case TypeCode.Double: return conv.ToDouble(null).Equals(value);
                        case TypeCode.Decimal: return conv.ToDecimal(null).Equals(value);
                    }
                }
                catch
                {
                    return false;
                }

                break;
        }

        return obj.Equals(value);
    }

    /// <summary>
    /// Returns a value indicating whether this instance is equal to a specified <see cref="Int9T"/> value.
    /// </summary>
    /// <param name="other">A <see cref="Int9T"/> value to compare to this instance.</param>
    /// <returns><see langword="true"/> if <paramref name="other"/> has the same value as this instance; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Int9T other) => value == other.value;

    /// <summary>
    /// Returns a value indicating whether this instance is equal to a specified <see cref="Int16"/> value.
    /// </summary>
    /// <param name="other">A <see cref="Int16"/> value to compare to this instance.</param>
    /// <returns><see langword="true"/> if <paramref name="other"/> has the same value as this instance; otherwise, <see langword="false"/>.</returns>
    public bool Equals(Int16 other) => value == other;

    /// <summary>
    /// Returns the hash code for this instance.
    /// </summary>
    /// <returns>A 32-bit signed integer hash code.</returns>
    public override int GetHashCode() => value.GetHashCode();

    #region Equality Operators

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int9T"/> instances are equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator ==(IConvertible left, Int9T right) => right.Equals(left);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int9T"/> instances are not equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator !=(IConvertible left, Int9T right) => !right.Equals(left);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int9T"/> instances are equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator ==(Int9T left, IConvertible right) => left.Equals(right);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int9T"/> instances are not equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator !=(Int9T left, IConvertible right) => !left.Equals(right);

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int9T"/> instances are equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator ==(Int9T left, Int9T right) => left.value == right.value;

    /// <summary>
    /// Returns a value indicating whether two <see cref="Int9T"/> instances are not equal.
    /// </summary>
    /// <param name="left">The first instance to compare.</param>
    /// <param name="right">The second instance to compare.</param>
    /// <returns><see langword="true"/> if the values of <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, <see langword="false"/>.</returns>
    public static bool operator !=(Int9T left, Int9T right) => left.value != right.value;

    #endregion

    #region Arithmetic Operators
    
    // Ternary arithmetic operators
    /// <summary>
    /// Adds two ternary numbers together, maintaining the original numeric type.
    /// </summary>
    /// <param name="left">The first ternary number.</param>
    /// <param name="right">The second ternary number.</param>
    /// <returns>A new ternary number of the same type containing the sum.</returns>
    public static Int9T operator +(Int9T left, Int9T right) => Create(left.value + right.value);

    /// <summary>
    /// Subtracts the second ternary number from the first, maintaining the original numeric type.
    /// </summary>
    /// <param name="left">The number to subtract from.</param>
    /// <param name="right">The number to subtract.</param>
    /// <returns>A new ternary number of the same type containing the difference.</returns>
    public static Int9T operator -(Int9T left, Int9T right) => Create(left.value - right.value);

    /// <summary>
    /// Multiplies two ternary numbers together, maintaining the original numeric type.
    /// </summary>
    /// <param name="left">The first number to multiply.</param>
    /// <param name="right">The second number to multiply.</param>
    /// <returns>A new ternary number of the same type containing the product.</returns>
    public static Int9T operator *(Int9T left, Int9T right) => Create(left.value * right.value);

    /// <summary>
    /// Divides the first ternary number by the second, maintaining the original numeric type.
    /// </summary>
    /// <param name="left">The dividend.</param>
    /// <param name="right">The divisor.</param>
    /// <returns>A new ternary number of the same type containing the quotient.</returns>
    public static Int9T operator /(Int9T left, Int9T right) => Create(left.value / right.value);

    /// <summary>
    /// Computes the remainder after dividing the first ternary number by the second.
    /// </summary>
    /// <param name="left">The dividend.</param>
    /// <param name="right">The divisor.</param>
    /// <returns>A new ternary number of the same type containing the remainder.</returns>
    public static Int9T operator %(Int9T left, Int9T right) => Create(left.value % right.value);

    // Unary arithmetic operators
    /// <summary>
    /// Returns the negation of a ternary number, maintaining the original numeric type.
    /// </summary>
    /// <param name="value">The ternary number to negate.</param>
    /// <returns>A new ternary number of the same type containing the negated value.</returns>
    public static Int9T operator -(Int9T value) => Create(-value.value);

    /// <summary>
    /// Returns the same ternary number (unary plus operator).
    /// </summary>
    /// <param name="value">The ternary number.</param>
    /// <returns>The same ternary number.</returns>
    public static Int9T operator +(Int9T value) => value;

    // Mixed arithmetic operators
    /// <summary>
    /// Adds a ternary number and a native numeric value, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The ternary number.</param>
    /// <param name="right">The native numeric value to add.</param>
    /// <returns>A new ternary number containing the sum.</returns>
    public static Int9T operator +(Int9T left, Int16 right) => Create(left.value + right);

    /// <summary>
    /// Adds a native numeric value and a ternary number, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The native numeric value to add.</param>
    /// <param name="right">The ternary number.</param>
    /// <returns>A new ternary number containing the sum.</returns>
    public static Int9T operator +(Int16 left, Int9T right) => Create(left + right.value);

    /// <summary>
    /// Subtracts a native numeric value from a ternary number, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The ternary number to subtract from.</param>
    /// <param name="right">The native numeric value to subtract.</param>
    /// <returns>A new ternary number containing the difference.</returns>
    public static Int9T operator -(Int9T left, Int16 right) => Create(left.value - right);

    /// <summary>
    /// Subtracts a ternary number from a native numeric value, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The native numeric value.</param>
    /// <param name="right">The ternary number to subtract.</param>
    /// <returns>A new ternary number containing the difference.</returns>
    public static Int9T operator -(Int16 left, Int9T right) => Create(left - right.value);

    /// <summary>
    /// Multiplies a ternary number by a native numeric value, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The ternary number.</param>
    /// <param name="right">The native numeric value to multiply by.</param>
    /// <returns>A new ternary number of the same type containing the product.</returns>
    public static Int9T operator *(Int9T left, Int16 right) => Create(left.value * right);

    /// <summary>
    /// Multiplies a native numeric value by a ternary number, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The native numeric value.</param>
    /// <param name="right">The ternary number to multiply by.</param>
    /// <returns>A new ternary number containing the product.</returns>
    public static Int9T operator *(Int16 left, Int9T right) => Create(left * right.value);

    /// <summary>
    /// Divides a ternary number by a native numeric value, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The ternary number to divide.</param>
    /// <param name="right">The native numeric value to divide by.</param>
    /// <returns>A new ternary number of the same type containing the quotient.</returns>
    public static Int9T operator /(Int9T left, Int16 right) => Create(left.value / right);

    /// <summary>
    /// Divides a native numeric value by a ternary number, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The native numeric value to divide.</param>
    /// <param name="right">The ternary number to divide by.</param>
    /// <returns>A new ternary number containing the quotient.</returns>
    public static Int9T operator /(Int16 left, Int9T right) => Create(left / right.value);

    /// <summary>
    /// Computes the remainder after dividing a ternary number by a native numeric value, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The ternary number to divide.</param>
    /// <param name="right">The native numeric value to divide by.</param>
    /// <returns>A new ternary number of the same type containing the remainder.</returns>
    public static Int9T operator %(Int9T left, Int16 right) => Create(left.value % right);

    /// <summary>
    /// Computes the remainder after dividing a native numeric value by a ternary number, maintaining the original ternary type.
    /// </summary>
    /// <param name="left">The native numeric value to divide.</param>
    /// <param name="right">The ternary number to divide by.</param>
    /// <returns>A new ternary number containing the remainder.</returns>
    public static Int9T operator %(Int16 left, Int9T right) => Create(left % right.value);
    #endregion
    
    #region Comparison Operators

    // Comparison operators with Int9T
    public static bool operator >(Int9T left, Int9T right) => left.value > right.value;
    public static bool operator <(Int9T left, Int9T right) => left.value < right.value;
    public static bool operator >=(Int9T left, Int9T right) => left.value >= right.value;
    public static bool operator <=(Int9T left, Int9T right) => left.value <= right.value;
    
    // Comparison operators with sbyte
    public static bool operator >(Int9T left, sbyte right) => left.value > right;
    public static bool operator <(Int9T left, sbyte right) => left.value < right;
    public static bool operator >=(Int9T left, sbyte right) => left.value >= right;
    public static bool operator <=(Int9T left, sbyte right) => left.value <= right;

    public static bool operator >(sbyte left, Int9T right) => left > right.value;
    public static bool operator <(sbyte left, Int9T right) => left < right.value;
    public static bool operator >=(sbyte left, Int9T right) => left >= right.value;
    public static bool operator <=(sbyte left, Int9T right) => left <= right.value;
    
    // Comparison operators with byte
    public static bool operator >(Int9T left, byte right) => left.value > right;
    public static bool operator <(Int9T left, byte right) => left.value < right;
    public static bool operator >=(Int9T left, byte right) => left.value >= right;
    public static bool operator <=(Int9T left, byte right) => left.value <= right;

    public static bool operator >(byte left, Int9T right) => left > right.value;
    public static bool operator <(byte left, Int9T right) => left < right.value;
    public static bool operator >=(byte left, Int9T right) => left >= right.value;
    public static bool operator <=(byte left, Int9T right) => left <= right.value;
    
    // Comparison operators with int
    public static bool operator >(Int9T left, int right) => left.value > right;
    public static bool operator <(Int9T left, int right) => left.value < right;
    public static bool operator >=(Int9T left, int right) => left.value >= right;
    public static bool operator <=(Int9T left, int right) => left.value <= right;

    public static bool operator >(int left, Int9T right) => left > right.value;
    public static bool operator <(int left, Int9T right) => left < right.value;
    public static bool operator >=(int left, Int9T right) => left >= right.value;
    public static bool operator <=(int left, Int9T right) => left <= right.value;
    
    // Comparison operators with uint
    public static bool operator >(Int9T left, uint right) => left.value > right;
    public static bool operator <(Int9T left, uint right) => left.value < right;
    public static bool operator >=(Int9T left, uint right) => left.value >= right;
    public static bool operator <=(Int9T left, uint right) => left.value <= right;

    public static bool operator >(uint left, Int9T right) => left > right.value;
    public static bool operator <(uint left, Int9T right) => left < right.value;
    public static bool operator >=(uint left, Int9T right) => left >= right.value;
    public static bool operator <=(uint left, Int9T right) => left <= right.value;
    
    // Comparison operators with short
    public static bool operator >(Int9T left, short right) => left.value > right;
    public static bool operator <(Int9T left, short right) => left.value < right;
    public static bool operator >=(Int9T left, short right) => left.value >= right;
    public static bool operator <=(Int9T left, short right) => left.value <= right;

    public static bool operator >(short left, Int9T right) => left > right.value;
    public static bool operator <(short left, Int9T right) => left < right.value;
    public static bool operator >=(short left, Int9T right) => left >= right.value;
    public static bool operator <=(short left, Int9T right) => left <= right.value;
    
    // Comparison operators with ushort
    public static bool operator >(Int9T left, ushort right) => left.value > right;
    public static bool operator <(Int9T left, ushort right) => left.value < right;
    public static bool operator >=(Int9T left, ushort right) => left.value >= right;
    public static bool operator <=(Int9T left, ushort right) => left.value <= right;

    public static bool operator >(ushort left, Int9T right) => left > right.value;
    public static bool operator <(ushort left, Int9T right) => left < right.value;
    public static bool operator >=(ushort left, Int9T right) => left >= right.value;
    public static bool operator <=(ushort left, Int9T right) => left <= right.value;
    
    // Comparison operators with long
    public static bool operator >(Int9T left, long right) => left.value > right;
    public static bool operator <(Int9T left, long right) => left.value < right;
    public static bool operator >=(Int9T left, long right) => left.value >= right;
    public static bool operator <=(Int9T left, long right) => left.value <= right;

    public static bool operator >(long left, Int9T right) => left > right.value;
    public static bool operator <(long left, Int9T right) => left < right.value;
    public static bool operator >=(long left, Int9T right) => left >= right.value;
    public static bool operator <=(long left, Int9T right) => left <= right.value;
    
    // Comparison operators with ulong
    public static bool operator >(Int9T left, ulong right) => left.CompareTo(right) > 0;
    public static bool operator <(Int9T left, ulong right) => left.CompareTo(right) < 0;
    public static bool operator >=(Int9T left, ulong right) => left.CompareTo(right) >= 0;
    public static bool operator <=(Int9T left, ulong right) => left.CompareTo(right) <= 0;

    public static bool operator >(ulong left, Int9T right) => right.CompareTo(left) < 0;
    public static bool operator <(ulong left, Int9T right) => right.CompareTo(left) > 0;
    public static bool operator >=(ulong left, Int9T right) => right.CompareTo(left) <= 0;
    public static bool operator <=(ulong left, Int9T right) => right.CompareTo(left) >= 0;
     
    // Comparison operators with float
    public static bool operator >(Int9T left, float right) => left.value > right;
    public static bool operator <(Int9T left, float right) => left.value < right;
    public static bool operator >=(Int9T left, float right) => left.value >= right;
    public static bool operator <=(Int9T left, float right) => left.value <= right;

    public static bool operator >(float left, Int9T right) => left > right.value;
    public static bool operator <(float left, Int9T right) => left < right.value;
    public static bool operator >=(float left, Int9T right) => left >= right.value;
    public static bool operator <=(float left, Int9T right) => left <= right.value;
     
    // Comparison operators with double
    public static bool operator >(Int9T left, double right) => left.value > right;
    public static bool operator <(Int9T left, double right) => left.value < right;
    public static bool operator >=(Int9T left, double right) => left.value >= right;
    public static bool operator <=(Int9T left, double right) => left.value <= right;

    public static bool operator >(double left, Int9T right) => left > right.value;
    public static bool operator <(double left, Int9T right) => left < right.value;
    public static bool operator >=(double left, Int9T right) => left >= right.value;
    public static bool operator <=(double left, Int9T right) => left <= right.value;
     
    // Comparison operators with decimal
    public static bool operator >(Int9T left, decimal right) => left.value > right;
    public static bool operator <(Int9T left, decimal right) => left.value < right;
    public static bool operator >=(Int9T left, decimal right) => left.value >= right;
    public static bool operator <=(Int9T left, decimal right) => left.value <= right;

    public static bool operator >(decimal left, Int9T right) => left > right.value;
    public static bool operator <(decimal left, Int9T right) => left < right.value;
    public static bool operator >=(decimal left, Int9T right) => left >= right.value;
    public static bool operator <=(decimal left, Int9T right) => left <= right.value;
     
    // Comparison operators with IComparable
    public static bool operator >(Int9T left, IComparable right) => left.CompareTo(right) > 0;
    public static bool operator <(Int9T left, IComparable right) => left.CompareTo(right) < 0;
    public static bool operator >=(Int9T left, IComparable right) => left.CompareTo(right) >= 0;
    public static bool operator <=(Int9T left, IComparable right) => left.CompareTo(right) <= 0;

    public static bool operator >(IComparable left, Int9T right) => right.CompareTo(left) < 0;
    public static bool operator <(IComparable left, Int9T right) => right.CompareTo(left) > 0;
    public static bool operator >=(IComparable left, Int9T right) => right.CompareTo(left) <= 0;
    public static bool operator <=(IComparable left, Int9T right) => right.CompareTo(left) >= 0;

    #endregion

    // ToString implementation
    /// <summary>
    /// Returns a string representation of this instance.
    /// </summary>
    public override string ToString() => Formatter.Format(this, null, null);
    /// <summary>
    /// Returns a string representation of this instance.
    /// </summary>
    public string ToString(string? format) =>Formatter.Format(this, format, null);
    /// <summary>
    /// Returns a string representation of this instance.
    /// </summary>
    public string ToString(IFormatProvider? provider) => Formatter.Format(this, null, provider);
    /// <summary>
    /// Returns a string representation of this instance.
    /// </summary>
    public string ToString(string? format, IFormatProvider? provider) =>Formatter.Format(this, format, provider);
    /// <summary>
    /// Returns a string representation of this instance, formatted balanced ternarily according to the specified format.
    /// </summary>
    public string ToString(ITernaryFormat format) => Formatter.Format(this, format);

    // Parsing methods

    /// <summary>
    /// Converts the string representation of a number to its <see cref="Int9T"/> equivalent.
    /// </summary>
    /// <param name="s">A string containing a number to convert.</param>
    /// <returns>A <see cref="Int9T"/> equivalent to the number contained in <paramref name="s"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="s"/> is <see langword="null"/>.</exception>
    /// <exception cref="FormatException"><paramref name="s"/> is not in the correct format.</exception>
    /// <exception cref="OverflowException"><paramref name="s"/> represents a number less than <see cref="Int9T.MinValue"/> or greater than <see cref="Int9T.MaxValue"/>.</exception>
    public static Int9T Parse(string s) => Create(Int16.Parse(s));

    /// <summary>
    /// Converts the string representation of a number in a specified style to its <see cref="Int9T"/> equivalent.
    /// </summary>
    /// <param name="s">A string containing a number to convert.</param>
    /// <param name="style">A bitwise combination of enumeration values that indicate the style elements that can be present in <paramref name="s"/>.</param>
    /// <returns>A <see cref="Int9T"/> equivalent to the number contained in <paramref name="s"/>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="s"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException"><paramref name="style"/> is not a <see cref="NumberStyles"/> value or <paramref name="style"/> includes the <see cref="NumberStyles.AllowHexSpecifier"/> value.</exception>
    /// <exception cref="FormatException"><paramref name="s"/> is not in a format compliant with <paramref name="style"/>.</exception>
    /// <exception cref="OverflowException"><paramref name="s"/> represents a number less than <see cref="Int9T.MinValue"/> or greater than <see cref="Int9T.MaxValue"/>.</exception>
    public static Int9T Parse(string s, NumberStyles style) => Create(Int16.Parse(s, style));

    /// <summary>
    /// Tries to convert the string representation of a number to its <see cref="Int9T"/> equivalent, and returns a value that indicates whether the conversion succeeded.
    /// </summary>
    /// <param name="s">A string containing a number to convert.</param>
    /// <param name="result">When this method returns, contains the <see cref="Int9T"/> value equivalent to the number contained in <paramref name="s"/> if the conversion succeeded, or zero if the conversion failed. This parameter is passed uninitialized.</param>
    /// <returns><see langword="true"/> if <paramref name="s"/> was converted successfully; otherwise, <see langword="false"/>.</returns>
    public static bool TryParse(string? s, out Int9T result)
    {
        bool success = Int16.TryParse(s, out Int16 value);
        result = new Int9T(value);
        return success;
    }

    /// <summary>
    /// Compares this instance to a specified object and returns an indication of their relative values.
    /// </summary>
    /// <param name="obj">An object to compare, or <see langword="null"/>.</param>
    /// <returns>
    /// A signed number indicating the relative values of this instance and <paramref name="obj"/>.
    /// Return Value Description:
    /// Less than zero: This instance is less than <paramref name="obj"/>.
    /// Zero: This instance is equal to <paramref name="obj"/>.
    /// Greater than zero: This instance is greater than <paramref name="obj"/> or <paramref name="obj"/> is <see langword="null"/>.
    /// </returns>
    /// <exception cref="ArgumentException"><paramref name="obj"/> is not a <see cref="Int9T"/> or a type that can be converted to an integer.</exception>
    public int CompareTo(object? obj)
    {
        if (obj == null) return 1;
        if (obj is Int9T other) return CompareTo(other);

        // For large numeric types that exceed Int9T's range, return -1 if greater than MaxValue, 1 if less than MinValue
        try
        {
            if (obj is Int16 typed) return value.CompareTo(typed);
            if (obj is long int64)
            {
                return int64 switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int16)int64)
                };
            }

            if (obj is uint uint32)
            {
                return uint32 > MaxValueConstant ? -1 : value.CompareTo((Int16)uint32);
            }

            if (obj is ulong uint64)
            {
                return uint64 > (long)MaxValueConstant ? -1 : value.CompareTo((Int16)uint64);
            }

            if (obj is short int16) return value.CompareTo(int16);
            if (obj is ushort uint16) return value.CompareTo(uint16);
            if (obj is byte byteVal) return value.CompareTo(byteVal);
            if (obj is sbyte sbyteVal) return value.CompareTo(sbyteVal);
            if (obj is float singleValue)
            {
                return singleValue switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int16)singleValue)
                };
            }

            if (obj is double doubleValue)
            {
                return doubleValue switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int16)doubleValue)
                };
            }

            if (obj is decimal decimalValue)
            {
                return decimalValue switch
                {
                    > MaxValueConstant => -1,
                    < MinValueConstant => 1,
                    _ => value.CompareTo((Int16)decimalValue)
                };
            }

            if (obj is IConvertible convertible)
            {
                switch (convertible.GetTypeCode())
                {
                    case TypeCode.Int16:
                    case TypeCode.UInt16:
                    case TypeCode.Byte:
                    case TypeCode.SByte:
                        return value.CompareTo(convertible.ToInt32(null));
                    case TypeCode.Int32:
                        return value.CompareTo(convertible.ToInt32(null));
                    case TypeCode.UInt32:
                        var uint32Value = convertible.ToUInt32(null);
                        if (uint32Value > MaxValueConstant) return -1;
                        return value.CompareTo((Int16)uint32Value);
                    case TypeCode.Int64:
                        var int64Value = convertible.ToInt64(null);
                        if (int64Value > MaxValueConstant) return -1;
                        if (int64Value < MinValueConstant) return 1;
                        return value.CompareTo((Int16)(int64Value));
                    case TypeCode.UInt64:
                        var uint64Value = convertible.ToUInt64(null);
                        if (uint64Value > (long)MaxValueConstant) return -1;
                        return value.CompareTo((Int16)uint64Value);
                    case TypeCode.Single:
                        var singleVal = convertible.ToSingle(null);
                        if (singleVal > MaxValueConstant) return -1;
                        if (singleVal < MinValueConstant) return 1;
                        return value.CompareTo((Int16)singleVal);
                    case TypeCode.Double:
                        var doubleVal = convertible.ToDouble(null);
                        if (doubleVal > MaxValueConstant) return -1;
                        if (doubleVal < MinValueConstant) return 1;
                        return value.CompareTo((Int16)doubleVal);
                    case TypeCode.Decimal:
                        var decimalVal = convertible.ToDecimal(null);
                        if (decimalVal > MaxValueConstant) return -1;
                        if (decimalVal < MinValueConstant) return 1;
                        return value.CompareTo((Int16)decimalVal);
                }
            }
        }
        catch (OverflowException)
        {
            // If conversion fails due to overflow, we can assume the value is outside our range
            return -1;
        }

        throw new ArgumentException("Object is not a valid type for comparison", nameof(obj));
    }

    /// <summary>
    /// Compares this instance to a specified <see cref="Int9T"/> object and returns an indication of their relative values.
    /// </summary>
    /// <param name="other">An <see cref="Int9T"/> object to compare.</param>
    /// <returns>
    /// A signed number indicating the relative values of this instance and <paramref name="other"/>.
    /// Return Value Description:
    /// Less than zero: This instance is less than <paramref name="other"/>.
    /// Zero: This instance is equal to <paramref name="other"/>.
    /// Greater than zero: This instance is greater than <paramref name="other"/>.
    /// </returns>
    public int CompareTo(Int9T other) => value.CompareTo(other.value);

    #region IConvertible Implementation

    public TypeCode GetTypeCode() => TypeCode.Int32;

    bool IConvertible.ToBoolean(IFormatProvider? provider) => value != 0;
    char IConvertible.ToChar(IFormatProvider? provider) => Convert.ToChar(value);
    sbyte IConvertible.ToSByte(IFormatProvider? provider) => Convert.ToSByte(value);
    byte IConvertible.ToByte(IFormatProvider? provider) => Convert.ToByte(value);
    short IConvertible.ToInt16(IFormatProvider? provider) => Convert.ToInt16(value);
    ushort IConvertible.ToUInt16(IFormatProvider? provider) => Convert.ToUInt16(value);
    int IConvertible.ToInt32(IFormatProvider? provider) => Convert.ToInt32(value);
    uint IConvertible.ToUInt32(IFormatProvider? provider) => Convert.ToUInt32(value);
    long IConvertible.ToInt64(IFormatProvider? provider) => Convert.ToInt64(value);
    ulong IConvertible.ToUInt64(IFormatProvider? provider) => Convert.ToUInt64(value);
    float IConvertible.ToSingle(IFormatProvider? provider) => Convert.ToSingle(value);
    double IConvertible.ToDouble(IFormatProvider? provider) => Convert.ToDouble(value);
    decimal IConvertible.ToDecimal(IFormatProvider? provider) => Convert.ToDecimal(value);
    DateTime IConvertible.ToDateTime(IFormatProvider? provider) => throw new InvalidCastException();
    string IConvertible.ToString(IFormatProvider? provider) => value.ToString(provider);

    object IConvertible.ToType(Type conversionType, IFormatProvider? provider) =>
        Convert.ChangeType(value, conversionType, provider);

    #endregion

    #region IUtf8SpanFormattable Implementation

    bool IUtf8SpanFormattable.TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
         => Formatter.TryFormat(value, utf8Destination, out bytesWritten, format, provider);

    #endregion

    #region IIncrementOperators/IDecrementOperators Implementation

    public static Int9T operator ++(Int9T value) => Create(value.value + 1);
    public static Int9T operator --(Int9T value) => Create(value.value - 1);

    #endregion

    static bool IEqualityOperators<Int9T, Int9T, bool>.operator ==(Int9T left, Int9T right) => left.value == right.value;
    static bool IEqualityOperators<Int9T, Int9T, bool>.operator !=(Int9T left, Int9T right) => left.value != right.value;

    #region Binary Operations

    
/// <summary>
/// Performs a left shift operation on the ternary number, maintaining the original numeric type.
/// </summary>
/// <param name="value">The ternary number to shift.</param>
/// <param name="shiftAmount">The number of positions to shift left. Negative values result in a right shift.</param>
/// <returns>A new ternary number of the same type containing the shifted value.</returns>
public static Int9T operator <<(Int9T value, int shiftAmount) => Create(value.value.Shift(-shiftAmount));

/// <summary>
/// Performs a right shift operation on the ternary number, maintaining the original numeric type.
/// </summary>
/// <param name="value">The ternary number to shift.</param>
/// <param name="shiftAmount">The number of positions to shift right. Negative values result in a left shift.</param>
/// <returns>A new ternary number of the same type containing the shifted value.</returns>
public static Int9T operator >> (Int9T value, int shiftAmount) => Create(value.value.Shift(shiftAmount));

/// <summary>
/// Performs an unsigned right shift operation on the ternary number, maintaining the original numeric type.
/// In this implementation, it behaves the same as the signed right shift.
/// </summary>
/// <param name="value">The ternary number to shift.</param>
/// <param name="shiftAmount">The number of positions to shift right. Negative values result in a left shift.</param>
/// <returns>A new ternary number of the same type containing the shifted value.</returns>
public static Int9T operator >>> (Int9T value, int shiftAmount) => Create(value.value.Shift(shiftAmount));

/// <summary>
/// Applies a unary operation to each trit in this ternary number. This operation converts the number to a TritArray.
/// </summary>
/// <param name="value">The ternary number to convert and operate on.</param>
/// <param name="operation">The unary operation to apply to each trit.</param>
/// <returns>A new TritArray containing the result of applying the operation.</returns>
/// <remarks>This operation causes an implicit conversion to TritArray before applying the operation.</remarks>
public static TritArray9 operator |(Int9T value, Func<Trit, Trit> operation)
{
    TritArray9 array = value;
    return array | operation;
}

/// <summary>
/// Combines each trit in this ternary number with the corresponding trit in the provided array. This operation converts the number to a TritArray.
/// </summary>
/// <param name="value">The ternary number to convert and combine.</param>
/// <param name="trits">The array of trits to combine with.</param>
/// <returns>A new TritArray containing the result of the operation.</returns>
/// <remarks>This operation causes an implicit conversion to TritArray before combining with the provided trits.</remarks>
public static TritArray9 operator |(Int9T value, Trit[] trits)
{
    TritArray9 array = value;
    return array | trits;
}

    #endregion

    #region Interface Static Members

    static Int9T ISignedNumber<Int9T>.NegativeOne => new(-1);
    static Int9T INumberBase<Int9T>.One => new(1);
    static Int9T INumberBase<Int9T>.Zero => new(0);
    static Int9T IAdditiveIdentity<Int9T, Int9T>.AdditiveIdentity => new(0);
    static Int9T IMultiplicativeIdentity<Int9T, Int9T>.MultiplicativeIdentity => new(1);

    static bool INumberBase<Int9T>.IsCanonical(Int9T value) => true;
    static bool INumberBase<Int9T>.IsComplexNumber(Int9T value) => false;
    static bool INumberBase<Int9T>.IsEvenInteger(Int9T value) => value.value % 2 == 0;
    static bool INumberBase<Int9T>.IsFinite(Int9T value) => true;
    static bool INumberBase<Int9T>.IsImaginaryNumber(Int9T value) => false;
    static bool INumberBase<Int9T>.IsInfinity(Int9T value) => false;
    static bool INumberBase<Int9T>.IsInteger(Int9T value) => true;
    static bool INumberBase<Int9T>.IsNaN(Int9T value) => false;
    static bool INumberBase<Int9T>.IsNegative(Int9T value) => value.value < 0;
    static bool INumberBase<Int9T>.IsNegativeInfinity(Int9T value) => false;
    static bool INumberBase<Int9T>.IsNormal(Int9T value) => value.value != 0;
    static bool INumberBase<Int9T>.IsOddInteger(Int9T value) => value.value % 2 != 0;
    static bool INumberBase<Int9T>.IsPositive(Int9T value) => value.value > 0;
    static bool INumberBase<Int9T>.IsPositiveInfinity(Int9T value) => false;
    static bool INumberBase<Int9T>.IsRealNumber(Int9T value) => true;
    static bool INumberBase<Int9T>.IsSubnormal(Int9T value) => false;
    static bool INumberBase<Int9T>.IsZero(Int9T value) => value.value == 0;

    static Int9T INumberBase<Int9T>.MaxMagnitude(Int9T x, Int9T y) =>
        Math.Abs(x.value) > Math.Abs(y.value) ? x : y;

    static Int9T INumberBase<Int9T>.MaxMagnitudeNumber(Int9T x, Int9T y) =>
        Math.Abs(x.value) > Math.Abs(y.value) ? x : y;

    static Int9T INumberBase<Int9T>.MinMagnitude(Int9T x, Int9T y) =>
        Math.Abs(x.value) < Math.Abs(y.value) ? x : y;

    static Int9T INumberBase<Int9T>.MinMagnitudeNumber(Int9T x, Int9T y) =>
        Math.Abs(x.value) < Math.Abs(y.value) ? x : y;

    static int INumberBase<Int9T>.Radix => 2;

    static Int9T INumberBase<Int9T>.Abs(Int9T value) =>
        value.value < 0 ? new((Int16)(-value.value)) : value;

    static Int9T INumberBase<Int9T>.Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) =>
        Create(Int16.Parse(s, style, provider));

    static Int9T INumberBase<Int9T>.Parse(string s, NumberStyles style, IFormatProvider? provider) =>
        Create(Int16.Parse(s, style, provider));

    static bool INumberBase<Int9T>.TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out Int9T result)
    {
        if (Int16.TryParse(s, style, provider, out var parsed))
        {
            result = Create(parsed);
            return true;
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int9T>.TryParse([NotNullWhen(true)] string? s, NumberStyles style, IFormatProvider? provider, out Int9T result)
    {
        if (Int16.TryParse(s, style, provider, out var parsed))
        {
            result = Create(parsed);
            return true;
        }

        result = default;
        return false;
    }

    #endregion

    #region ISpanFormattable/ISpanParsable Implementation

    static Int9T ISpanParsable<Int9T>.Parse(ReadOnlySpan<char> s, IFormatProvider? provider) =>
        new(Int16.Parse(s, NumberStyles.Integer, provider));

    static bool ISpanParsable<Int9T>.TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Int9T result)
    {
        if (Int16.TryParse(s, NumberStyles.Integer, provider, out var value))
        {
            result = new(value);
            return true;
        }

        result = default;
        return false;
    }

    bool ISpanFormattable.TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) 
        => Formatter.TryFormat(value, destination, out charsWritten, format, provider);

               static Int9T IParsable<Int9T>.Parse(string s, IFormatProvider? provider) =>
        new(Int16.Parse(s, NumberStyles.Integer, provider));

    static bool IParsable<Int9T>.TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out Int9T result)
    {
        if (Int16.TryParse(s, NumberStyles.Integer, provider, out var value))
        {
            result = new(value);
            return true;
        }

        result = default;
        return false;
    }
    #endregion

    #region Generic Conversions

    static bool INumberBase<Int9T>.TryConvertFromChecked<TOther>(TOther value, out Int9T result)
    {
        if (value is IConvertible conv)
        {
            try
            {
                var intValue = conv.ToInt16(null);
                if (intValue >= MinValueConstant && intValue <= MaxValueConstant)
                {
                    result = Create(intValue);
                    return true;
                }
            }
            catch
            {
                // Fall through to default
            }
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int9T>.TryConvertFromSaturating<TOther>(TOther value, out Int9T result)
    {
        if (value is IConvertible conv)
        {
            try
            {
                var intValue = conv.ToInt16(null);
                result = Create(intValue);
                return true;
            }
            catch
            {
                // Fall through to default
            }
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int9T>.TryConvertFromTruncating<TOther>(TOther value, out Int9T result)
    {
        if (value is IConvertible conv)
        {
            try
            {
                var intValue = conv.ToInt16(null);
                result = Create(intValue);
                return true;
            }
            catch
            {
                // Fall through to default
            }
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int9T>.TryConvertToChecked<TOther>(Int9T value, [MaybeNullWhen(false)] out TOther result)
        where TOther : default
    {
        if (typeof(TOther) == typeof(Int16))
        {
            result = (TOther)(object)value.value;
            return true;
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int9T>.TryConvertToSaturating<TOther>(Int9T value, [MaybeNullWhen(false)] out TOther result)
        where TOther : default
    {
        if (typeof(TOther) == typeof(Int16))
        {
            result = (TOther)(object)value.value;
            return true;
        }

        result = default;
        return false;
    }

    static bool INumberBase<Int9T>.TryConvertToTruncating<TOther>(Int9T value, [MaybeNullWhen(false)] out TOther result)
        where TOther : default
    {
        if (typeof(TOther) == typeof(Int16))
        {
            result = (TOther)(object)value.value;
            return true;
        }

        result = default;
        return false;
    }

    #endregion
}