// <auto-generated />
#nullable enable
namespace Ternary3;

using Formatting;
using Operators;
using System.Diagnostics;
using TritArrays;

/// <summary>
/// Represents a fixed-size array of 27 trits (ternary digits).
/// </summary>
[DebuggerDisplay("{DebugView()}")]
public struct TritArray27 : ITritArray<TritArray27>
{
    private const UInt32 BitMask = 0b111111111111111111111111111;
    private const int NumberOfTrits = 27;
    internal UInt32 Positive;
    internal UInt32 Negative;

    /// <summary>
    /// Represents the minimum value that a TritArray27 can have (all trits set to -1).
    /// </summary>
    public static readonly TritArray27 MinValue = new(BitMask, 0);

    /// <summary>
    /// Represents the maximum value that a TritArray27 can have (all trits set to 1).
    /// </summary>
    public static readonly TritArray27 MaxValue = new(0, BitMask);

    /// <summary>
    /// Represents a TritArray27 with all trits set to zero.
    /// </summary>
    public static readonly TritArray27 Zero = new();

    /// <summary>
    /// Initializes a new instance of the TritArray27 struct with all trits set to zero.
    /// </summary>
    public TritArray27()
    {
    }

    private TritArray27(UInt32Pair trits)
    {
        Negative = trits.Negative;
        Positive = trits.Positive;
    }

    /// <summary>
    /// Initializes a new instance of the TritArray27 struct with the specified negative and positive bits.
    /// </summary>
    /// <param name="negative">The negative bits representing the trits.</param>
    /// <param name="positive">The positive bits representing the trits.</param>
    internal TritArray27(UInt32 negative, UInt32 positive)
    {
        Negative = negative;
        Positive = positive;
    }

    /// <summary>
    /// Gets or sets the trit at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index of the trit to get or set (must be between 0 and 26).</param>
    /// <returns>The trit at the specified index.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when index is less than 0 or greater than 26.</exception>
    public Trit this[int index]
    {
        get => index is >= 0 and < NumberOfTrits 
                ? TritConverter.GetTrit(Negative, Positive, index)
                : throw new ArgumentOutOfRangeException(nameof(index), $"Index must be between 0 and {NumberOfTrits-1}.");
        set
        {
            if (index is < 0 or >= NumberOfTrits)
            {
                throw new ArgumentOutOfRangeException(nameof(index), $"Index must be between 0 and {NumberOfTrits-1}.");
            }
            TritConverter.SetTrit(ref Negative, ref Positive, index, value);
        }
    }
    
    /// <summary>
    /// Gets or sets the trit at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index of the trit to get or set (must be between 0 and 26).</param>
    /// <returns>The trit at the specified index.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when index is less than 0 or greater than 26.</exception>
    public Trit this[Index index]
    {
        get => index.IsFromEnd ? this[NumberOfTrits - index.Value] : this[index.Value];
        set
        {
            if (index.IsFromEnd)
            {
                this[NumberOfTrits - index.Value] = value;
            }
            else
            {
                this[index.Value] = value;
            }
        }
    }

    /// <summary>
    /// Gets the length of the trit array, which is always 27.
    /// </summary>
    public int Length => NumberOfTrits;

    /// <summary>
    /// Applies a unary operation to each trit in the array.
    /// </summary>
    /// <param name="array">The source array.</param>
    /// <param name="operation">The unary operation to apply to each trit.</param>
    /// <returns>A new TritArray27 with the operation applied to each trit.</returns>
    public static TritArray27 operator |(TritArray27 array, Func<Trit, Trit> operation)
        => array | new UnaryTritOperator(operation);

    /// <summary>
    /// Applies a lookup table operation to each trit in the array.
    /// </summary>
    /// <param name="array">The source array.</param>
    /// <param name="table">The lookup table containing the transformation values.</param>
    /// <returns>A new TritArray27 with the lookup operation applied to each trit.</returns>
    public static TritArray27 operator |(TritArray27 array, Trit[] table)
        => array | new UnaryTritOperator(table);

    /// <summary>
    /// Creates a binary operation context for this array.
    /// </summary>
    /// <param name="array">The source array.</param>
    /// <param name="operation">The binary operation to be applied.</param>
    /// <returns>A LookupTritArray27Operator that can be used to apply the operation with another array.</returns>
    public static LookupTritArray27Operator operator |(TritArray27 array, Func<Trit, Trit, Trit> operation)
        => new LookupTritArray27Operator(array, operation);

    public static LookupTritArray27Operator operator |(TritArray27 array, BinaryTritOperator table)
        => new LookupTritArray27Operator(array, table);

    public static LookupTritArray27Operator operator |(TritArray27 array, Trit[,] table)
        => new LookupTritArray27Operator(array, table);


    /// <summary>
    /// Performs a left bitwise shift on the trit array.
    /// </summary>
    /// <param name="array">The source array.</param>
    /// <param name="shift">The number of positions to shift.</param>
    /// <returns>A new TritArray27 with the bits shifted to the left.</returns>
    public static TritArray27 operator <<(TritArray27 array, int shift)
    {
        return shift switch
        {
            >= NumberOfTrits => Zero,
            < 0 => array >> -shift,
            _ => new() { Positive = (UInt32)((array.Positive << shift) & BitMask), Negative = (UInt32)((array.Negative << shift) & BitMask) }
        };
    }

    /// <summary>
    /// Performs a right bitwise shift on the trit array.
    /// </summary>
    /// <param name="array">The source array.</param>
    /// <param name="shift">The number of positions to shift.</param>
    /// <returns>A new TritArray27 with the bits shifted to the right.</returns>
    public static TritArray27 operator >> (TritArray27 array, int shift)
    {
        return shift switch
        {
            >= NumberOfTrits => Zero,
            < 0 => array << -shift,
            _ => new() { Positive = (UInt32)(array.Positive >> shift), Negative = (UInt32)(array.Negative >> shift) }
        };
    }

    /// <summary>
    /// Adds two TritArray27 values together.
    /// </summary>
    /// <param name="value1">The first value to add.</param>
    /// <param name="value2">The second value to add.</param>
    /// <returns>A new TritArray27 representing the sum of the two values.</returns>
    public static TritArray27 operator +(TritArray27 value1, TritArray27 value2)
    {
        Calculator.AddBalancedTernary(value1.Negative, value1.Positive, value2.Negative, value2.Positive, out var negative, out var positive);
        return new() { Negative = (UInt32)negative, Positive = (UInt32)positive };
    }

    /// <summary>
    /// Subtracts one TritArray27 value from another.
    /// </summary>
    /// <param name="value1">The value to subtract from.</param>
    /// <param name="value2">The value to subtract.</param>
    /// <returns>A new TritArray27 representing the difference between the two values.</returns>
    public static TritArray27 operator -(TritArray27 value1, TritArray27 value2)
    {
        Calculator.AddBalancedTernary(value1.Negative, value1.Positive, value2.Positive, value2.Negative, out var negative, out var positive);
        return new() { Negative = (UInt32)negative, Positive = (UInt32)positive };
    }

    #region Conversion Operators

    /// <summary>
    /// Creates a TritArray27 from an integer value.
    /// </summary>
    /// <param name="value">The integer value to convert.</param>
    /// <returns>A new TritArray27 representing the value in balanced ternary.</returns>
    private static TritArray27 Create(long value)
    {
        TritConverter.To32Trits(value, out var negative, out var positive);
        return new() { Negative = (UInt32)negative, Positive = (UInt32)positive };
    }

    /// <summary>
    /// Defines an implicit conversion of an Int27T to a TritArray27.
    /// </summary>
    /// <param name="value">The Int27T value to convert.</param>
    /// <returns>A TritArray27 representing the same value.</returns>
    public static implicit operator TritArray27(Int27T value)
    {
        // Cast to long to get the numeric value instead of trying to access a non-existent Value property
        TritConverter.To32Trits(value, out var negative, out var positive);
        return new() { Negative = (UInt32)negative, Positive = (UInt32)positive };
    }

    /// <summary>
    /// Defines an implicit conversion of a TritArray27 to an Int27T.
    /// </summary>
    /// <param name="array">The TritArray27 to convert.</param>
    /// <returns>An Int27T representing the same value.</returns>
    public static implicit operator Int27T(TritArray27 array) => (Int64)TritConverter.ToInt64(array.Negative, array.Positive);
    
    
       /// <summary>
       /// Defines an implicit conversion of an int to a TritArray27.
       /// </summary>
       /// <param name="value">The int value to convert.</param>
       /// <returns>A TritArray27 representing the same value.</returns>
       public static implicit operator TritArray27(int value) => Create(value);

       /// <summary>
       /// Defines an explicit conversion of a TritArray27 to an int.
       /// </summary>
       /// <param name="array">The TritArray27 to convert.</param>
       /// <returns>An int representing the same value.</returns>
       public static explicit operator int(TritArray27 array) => (int)TritConverter.ToInt64(array.Negative & BitMask, array.Positive & BitMask);

       /// <summary>
       /// Defines an implicit conversion of a long to a TritArray27.
       /// </summary>
       /// <param name="value">The long value to convert.</param>
       /// <returns>A TritArray27 representing the same value.</returns>
       public static implicit operator TritArray27(long value) => Create(value);

       /// <summary>
       /// Defines an implicit conversion of a TritArray27 to a long.
       /// </summary>
       /// <param name="array">The TritArray27 to convert.</param>
       /// <returns>A long representing the same value.</returns>
       public static implicit operator long(TritArray27 array) => TritConverter.ToInt64(array.Negative & BitMask, array.Positive & BitMask);

    #endregion

    /// <inheritdoc/>   
    public override int GetHashCode() => HashCode.Combine(Negative.GetHashCode(), Positive.GetHashCode());
    
    /// <inheritdoc/>  
    public override bool Equals(object? obj) => obj is TritArray27 other && Equals(other); 
    
    /// <inheritdoc/>  
    public bool Equals(TritArray27 other) => Negative == other.Negative && Positive == other.Positive;
    
    internal string DebugView() => $"{this} ({this:ter})";

    // ToString implementation
    /// <summary>
    /// Returns a string representation of the TritArray27.
    /// </summary>
    public override string ToString() => Formatter.Format(this, null, null);
    /// <summary>
    /// Returns a string representation of the TritArray27.
    /// </summary>
    public string ToString(string? format) =>Formatter.Format(this, format, null);
    /// <summary>
    /// Returns a string representation of the TritArray27.
    /// </summary>
    public string ToString(IFormatProvider? provider) => Formatter.Format(this, null, provider);
    /// <summary>
    /// Returns a string representation of the TritArray27.
    /// </summary>
    public string ToString(string? format, IFormatProvider? provider) =>Formatter.Format(this, format, provider);
    /// <summary>
   /// Returns a string representation of this instance, formatted balanced ternarily according to the specified format.
    /// </summary>
    public string ToString(ITernaryFormat format) => Formatter.Format((ITritArray)this, format);
}