// <auto-generated />
namespace Ternary3;

internal readonly struct UInt32Pair(UInt32 negative, UInt32 positive)
{
     private readonly UInt64 packed = (UInt64)(((UInt64)negative << 32) | positive);
     public UInt32 Negative => (UInt32)(packed >> 32);
     public UInt32 Positive => (UInt32)packed;
}
